name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.12
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: gccemacs-sierra
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A emacsGccSierra
    - run: echo OK
